name: nav_marker
description: nav_marker is a Flutter package that enables navigation of markers on flutter_map
version: 0.1.0

homepage: https://github.com/khasij3/nav_marker

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
